# Generated by Django 5.1.3 on 2024-12-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_alter_documentoboleto_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='endereco',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
